### ISSUE TITLE
somtimes canot get imports

### ISSUE THREAD

**Issue by Jhinxs** [Workshell/pe#6]
somtimes canot get imports,but can use dumpbim or some tools get imports

**Comment by lkinsella** [comment]
Curious.

Can you run it against the `pei-changes` branch and see if you still have issues? We did refactor that bit but we've yet to bring it into `master` yet so I'm wondering if that will resolve it.

If not can you supply the offending executable? I'd be interested in seeing where it goes wrong.

**Comment by lkinsella** [comment]
Closing this as stale.
