### ISSUE TITLE
Bug in parsing VS_VERSION_INFO

### ISSUE THREAD

**Issue by stjeong** [Workshell/pe#9]
At the line of code, https://github.com/Workshell/pe/blob/8477a41a88c7618d8dbae7b29c3da324ffcdcb1b/src/Workshell.PE.Resources/Version/VersionResource.cs#L82

It shows that VarFileInfo block must be after StringFileInfo block. Then, for example, it's OK to parse like this,

```
VS_VERSION_INFO VERSIONINFO
 FILEVERSION 1,0,0,1
 PRODUCTVERSION 1,0,0,1
 FILEFLAGSMASK 0x3fL
 FILEFLAGS 0x0L
 FILEOS 0x40004L
 FILETYPE 0x1L
 FILESUBTYPE 0x0L
BEGIN

    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "041204b0"
        BEGIN
            VALUE "CompanyName", "TODO: <Company name>"
            VALUE "FileDescription", "TODO: <File description>"
            VALUE "FileVersion", "1.0.0.1"
            VALUE "InternalName", "ConsoleA.exe"
            VALUE "LegalCopyright", "Copyright (C) 2024"
            VALUE "OriginalFilename", "ConsoleA.exe"
            VALUE "ProductName", "TODO: <Product name>"
            VALUE "ProductVersion", "1.0.0.1"
        END
    END

    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x412, 1200
    END

END
```

However, VarFileInfo block and StringFileInfo block is not ordered, therefore, it's possible to define like this,

```
BEGIN

    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x412, 1200
    END

    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "041204b0"
        BEGIN
            VALUE "CompanyName", "TODO: <Company name>"
            VALUE "FileDescription", "TODO: <File description>"
            VALUE "FileVersion", "1.0.0.1"
            VALUE "InternalName", "ConsoleA.exe"
            VALUE "LegalCopyright", "Copyright (C) 2024"
            VALUE "OriginalFilename", "ConsoleA.exe"
            VALUE "ProductName", "TODO: <Product name>"
            VALUE "ProductVersion", "1.0.0.1"
        END
    END

END
```

In this case, VersionResource.GetInfoAsync will throw an exception.

```
Unhandled exception. System.IO.IOException: Could not read uint16 from stream.
   at Workshell.PE.Extensions.StreamExtensions.ReadUInt16Async(Stream stream)
   at Workshell.PE.Resources.Version.StringFileInfo.LoadStringAsync(Stream stream)
   at Workshell.PE.Resources.Version.StringFileInfo.LoadTableAsync(Stream stream)
   at Workshell.PE.Resources.Version.StringFileInfo.LoadAsync(Stream stream)
   at Workshell.PE.Resources.Version.VersionResource.GetInfoAsync(ResourceLanguage language)
```

**Comment by lkinsella** [comment]
Ahh interesting yeh I'd made some assumptions there it seems. Really given both blocks share the same set of initial fields I should read those in, check the key (VarFileInfo or StringFileInfo) and then construct the correct type.

**Comment by lkinsella** [comment]
Give this a go - https://github.com/Workshell/pe/tree/feature/issue-9

This should handle it in any order now. Internally I also switched to collections so that I can support an arbitrary number of each, however the docs say:

> An array of zero or one [StringFileInfo](https://learn.microsoft.com/en-us/windows/win32/menurc/stringfileinfo) structures, and zero or one [VarFileInfo](https://learn.microsoft.com/en-us/windows/win32/menurc/varfileinfo) structures that are children of the current VS_VERSIONINFO structure.

So from each collection I just return `FirstOrDefault()` for now.

**Comment by stjeong** [comment]
I checked issue-9 branch works well. :) What a fast patch!
